name = "MarginalTreatmentEffects"
uuid = "93ddfb51-2dc3-4de7-87ac-99e501536a02"
authors = ["Omkar A. Katta <omkarakatta@gmail.com>",
           "A. Torgovitsky <atorgovitsky@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MarginalTreatmentEffectsWithMultipleInstruments = "e8ccf7cf-21b5-4ee4-a618-165bb004bb9c"
